// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SketchCore.Core.Data;
using System;

namespace SketchCore.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20170830025407_Update StockPhoto entity")]
    partial class UpdateStockPhotoentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SketchCore.Core.Models.StockPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .HasMaxLength(256);

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(256);

                    b.Property<string>("Copyright")
                        .HasMaxLength(256);

                    b.Property<string>("Description");

                    b.Property<DateTime>("ImportedDate");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(256);

                    b.Property<string>("PublishedDate")
                        .HasMaxLength(256);

                    b.Property<string>("Rating")
                        .HasMaxLength(256);

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasAlternateKey("UniqueId");

                    b.ToTable("StockPhoto");
                });

            modelBuilder.Entity("SketchCore.Core.Models.Thumbnail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Height");

                    b.Property<int?>("PhotoId");

                    b.Property<string>("Url")
                        .HasMaxLength(512);

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("Thumbnail");
                });

            modelBuilder.Entity("SketchCore.Core.Models.Thumbnail", b =>
                {
                    b.HasOne("SketchCore.Core.Models.StockPhoto", "Photo")
                        .WithMany("Thumbnails")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
