// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SketchCore.Core.Data;
using System;

namespace SketchCore.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SketchCore.Core.Models.StockPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ImportedDate");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(256);

                    b.Property<string>("PublishedDate")
                        .HasMaxLength(256);

                    b.Property<string>("Rating")
                        .HasMaxLength(256);

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasAlternateKey("UniqueId");

                    b.ToTable("StockPhoto");
                });

            modelBuilder.Entity("SketchCore.Core.Models.StockPhoto", b =>
                {
                    b.OwnsOne("SketchCore.Core.Models.OEmbedInfo", "OEmbedInfo", b1 =>
                        {
                            b1.Property<int>("StockPhotoId");

                            b1.Property<string>("AuthorName")
                                .HasMaxLength(256);

                            b1.Property<string>("AuthorUrl")
                                .HasMaxLength(256);

                            b1.Property<int>("Height");

                            b1.Property<string>("ProviderName")
                                .HasMaxLength(256);

                            b1.Property<string>("ProviderUrl")
                                .HasMaxLength(256);

                            b1.Property<int>("ThumbnailHeight");

                            b1.Property<string>("ThumbnailUrl")
                                .HasMaxLength(256);

                            b1.Property<int>("ThumbnailWidth");

                            b1.Property<string>("Title")
                                .HasMaxLength(256);

                            b1.Property<string>("Type")
                                .HasMaxLength(256);

                            b1.Property<string>("Url")
                                .HasMaxLength(256);

                            b1.Property<string>("Version")
                                .HasMaxLength(256);

                            b1.Property<int>("Width");

                            b1.ToTable("StockPhoto");

                            b1.HasOne("SketchCore.Core.Models.StockPhoto")
                                .WithOne("OEmbedInfo")
                                .HasForeignKey("SketchCore.Core.Models.OEmbedInfo", "StockPhotoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
